spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health
  metrics:
    export:
      prometheus:
        enabled: true
